name: Build and deploy .NET Core application to Web App pinventoryapi
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: pinventoryapi
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  CONFIGURATION: Production
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: ./src
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}/Inventory.API/Inventory.API.csproj"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}/Inventory.API/Inventory.API.csproj" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}/Inventory.API/Inventory.API.csproj" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}/Inventory.API/Inventory.API.csproj" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.pinventoryapi_583A }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      env:
        ConnectionStrings.DbConnect: ${{ secrets.SQL_SERVER }}
        ConnectionStrings.Redis: ${{ secrets.REDIS_SERVER }}
        JWTBearer.ValidAudience: ${{ secrets.JWT_AUDIENCE}}
        JWTBearer.SecretKey: ${{ secrets.JWT_KEY}}
        Cors: ${{secrets.CORS}}
        AppName: ${{secrects.APPNAME}}
